version: "3"
services:
  dev:
    build: ./
    image: dev:1.0.0
    stdin_open: true
    tty: true
    environment:
      - PATH=$PATH:/usr/local/go/bin
    #network_mode: "host"
    ports:
      - 8081:8081
      #- 80:80
    volumes:
      - ./:/develop
    working_dir: /develop
