version: "3"
services:
  dev:
    build: ./
    image: dev:1.0.0
    stdin_open: true
    tty: true
    #network_mode: "host"
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./:/develop
