version: "3"
services:
  test:
    build: ./
    image: portal:1.0.0
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - /home/jaeyoungcho/develop/work/portal:/root/develop/work/portal
      - /home/jaeyoungcho/develop/work/logs:/root/develop/work/logs
