# Generated by Django 2.1 on 2018-09-28 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 0, 2, 35, 833742, tzinfo=utc)),
        ),
    ]
