# Generated by Django 2.1 on 2018-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0009_auto_20181019_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
