# Generated by Django 2.1 on 2018-10-23 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0010_auto_20181023_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform_id',
            field=models.CharField(default=datetime.datetime(2018, 10, 23, 11, 13, 16, 708962, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobby',
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('platform', 'platform_id')},
        ),
    ]
