# Generated by Django 2.1 on 2018-10-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0012_auto_20181023_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
    ]
