# Generated by Django 2.1 on 2018-10-23 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_model', '0014_auto_20181023_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'platform', 'platform_id')},
        ),
    ]
