# Generated by Django 2.0.5 on 2018-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_noti_trigger_count', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
