# Generated by Django 2.0.5 on 2018-05-27 09:23

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email_noti_trigger_count', models.PositiveIntegerField(default=2, verbose_name='Signal count for the email notification about user registration.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
